trigger:
- master

pool:
  name: default

steps:
- script: |
    az group create --name orires --location eastus
    az deployment group create --resource-group orires --template-file res.json --parameters res.parameters.json
  displayName: 'deploy storage account and server'
